Bluebook/models/Leitor.py
from database import obter_conexao

class Leitor():
    

    @classmethod
    def all(cls):
        conn = obter_conexao()  
        cursor = conn.cursor(dictionary=True)

        cursor.execute('SELECT * FROM tb_leitores')
        consulta_usuarios = cursor.fetchall()
        conn.commit()
        cursor.close()
        conn.close()

        return consulta_usuarios
    
    @classmethod
    def cadastro(cls, nome, email, telefone, endereco):
        conn = obter_conexao()  
        cursor = conn.cursor()      
        cursor.execute("INSERT INTO tb_leitores (lei_nome, lei_email, lei_telefone, lei_endereco) VALUES (%s, %s, %s, %s)", (nome, email, telefone, endereco))
        conn.commit()
        conn.close()
    
    @classmethod
    def listar(cls, order_by):
        conn = obter_conexao()  
        cursor = conn.cursor(dictionary=True)
        query = f'SELECT * FROM tb_leitores ORDER BY lei_nome {order_by}'
        cursor.execute(query)
        leitores = cursor.fetchall()
        cursor.close()
        conn.close()
        return leitores
    @classmethod
    def one(cls, id):
        conn = obter_conexao()  
        cursor = conn.cursor(dictionary=True)
        query = f'SELECT * FROM tb_leitores where lei_id = {id}'
        cursor.execute(query)
        leitor = cursor.fetchone()
        cursor.close()
        conn.close()
        return leitor
    @classmethod
    def delete(cls,id):
        conn = obter_conexao()
        cursor = conn.cursor()
        cursor.execute('DELETE FROM tb_leitores WHERE lei_id = %s', (id,))
        conn.commit()
        cursor.close()
        conn.close()
    @classmethod
    def update(cls, id, nome, email, telefone, endereco):
        conn = obter_conexao()
        cursor = conn.cursor()

        query = 'UPDATE tb_leitores SET lei_nome = %s, lei_email = %s, lei_telefone = %s, lei_endereco = %s WHERE lei_id = %s'
        cursor.execute(query, (nome, email, telefone, endereco,id))
        conn.commit()
        cursor.close()
        conn.close()

Bluebook/models/book.py
from database import obter_conexao

class Book():

    @classmethod
    def cadastro(cls, titulo, autor, genero, isbn, quant_estoque):

        conn = obter_conexao()  
        cursor = conn.cursor()      
        cursor.execute("INSERT INTO tb_books (boo_titulo, boo_autor, boo_genero, boo_isbn, boo_quant_estoque) VALUES (%s, %s, %s, %s, %s)", (titulo, autor,genero, isbn, quant_estoque ))
        conn.commit()
        conn.close()

    @classmethod
    def listar(cls, order_by):

        conn = obter_conexao()  
        cursor = conn.cursor(dictionary=True)
        query = f'SELECT * FROM tb_books ORDER BY boo_titulo {order_by}'
        cursor.execute(query)
        books = cursor.fetchall()
        cursor.close()
        conn.close()
        return books
    
    @classmethod
    def all(cls):
        conn = obter_conexao()  
        cursor = conn.cursor(dictionary=True)
        cursor.execute('SELECT * FROM tb_books')
        consulta_livros = cursor.fetchall()
        conn.commit()
        cursor.close()
        conn.close()
        return consulta_livros
    @classmethod
    def one(cls, id):
        conn = obter_conexao()  
        cursor = conn.cursor(dictionary=True)
        cursor.execute(f'SELECT * FROM tb_books where boo_id = {id}')
        consulta_livros = cursor.fetchone()
        conn.commit()
        cursor.close()
        conn.close()
        return consulta_livros
    
    @classmethod
    def delete(cls,id):
        conn = obter_conexao()
        cursor = conn.cursor()
        cursor.execute('DELETE FROM tb_books WHERE boo_id = %s', (id,))
        conn.commit()
        cursor.close()
        conn.close()
    @classmethod
    def update(cls, id, titulo, autor, genero, isbn, quant_estoque):
        conn = obter_conexao()
        cursor = conn.cursor()

        query = 'UPDATE tb_books SET boo_titulo = %s, boo_autor = %s, boo_genero = %s, boo_isbn = %s, boo_quant_estoque = %s WHERE boo_id = %s'
        cursor.execute(query, (titulo,autor,genero,isbn,quant_estoque,id))
        conn.commit()
        cursor.close()
        conn.close()

Bluebook/controllers/Book.py
from flask import Blueprint, render_template, request, url_for, redirect
from models.Book import Book
from models.Lending import Lending
from database import obter_conexao
from flask_login import login_required, current_user

bp = Blueprint("books", __name__, url_prefix="/books")


@bp.route('/register_book', methods=['GET', 'POST'])
@login_required
def register_book():
    if request.method == 'POST':
        titulo = request.form["titulo"]
        autor = request.form["autor"]
        genero = request.form["genero"]
        quant_estoque = request.form["estoque"]
        isbn = request.form["isbn"]

        Book.cadastro(titulo, autor, genero, isbn, quant_estoque)
        return redirect(url_for('books.listar_book'))
    
    books= Book.listar(order_by='')
    user = current_user
    return render_template('book.html', books=books, user = user)

@bp.route('/listar_book', methods=['GET', 'POST'])
@login_required
def listar_book():

    books= Book.listar(order_by='asc')
    if request.method == 'POST':
        order_by = request.form['status']

        
        books = Book.listar(order_by=order_by)
    user = current_user
    return render_template('book.html', books = books, user = user)

@bp.route('/dados_livro')
@login_required
def dados_livros():
    books = Book.all()
    user = current_user
    return render_template("dados_livros.html", books=books, user=user)


@bp.route('/editar_book/<int:id>', methods=['GET', 'POST'])
@login_required
def editar_book(id):
    

    if request.method == 'POST':
        titulo = request.form.get('titulo')
        autor = request.form.get('autor')
        genero = request.form.get('genero')
        isbn = request.form.get('isbn')
        estoque = request.form.get('estoque')
        Book.update(id,titulo, autor, genero, isbn, estoque)
        return redirect(url_for('books.listar_book'))
    book = Book.one(id)
    user = current_user
    return render_template('editar_livros.html', book = book, user = user)


@bp.route('/apagar_book/<int:id>')
@login_required
def excluir_book(id):
    lendings = Lending.listar("")
    for lending in lendings:
        if id == lending['len_boo_id']:
            mensagem = "Esse Livro está sendo emprestado, Impossível Excluir"
            books = Book.all()
            user = current_user
            return render_template("dados_livros.html", books=books, mensagem = mensagem, user=user)
    Book.delete(id)
    return redirect(url_for('books.listar_book'))

Bluebook/controllers/Leitor.py
from flask import Blueprint, render_template, request, url_for, redirect
from models.Leitor import Leitor
from models.Lending import Lending
from database import obter_conexao
from flask_login import login_required, current_user

bp = Blueprint("leitores", __name__, url_prefix="/leitores")


@bp.route('/register_leitor', methods=['POST', 'GET'])
@login_required
def register_leitor():
    if request.method == 'POST':
        nome = request.form["nome"]
        email = request.form["email"]
        telefone = request.form["telefone"]
        endereco = request.form['endereco']

        Leitor.cadastro(nome, email, telefone, endereco)

        return redirect(url_for('leitores.listar_leitor'))
    leitores = Leitor.all()
    user = current_user
    return render_template('leitor.html',leitores = leitores, user = user)


@bp.route('/listar_leitor', methods=['POST', 'GET'])
@login_required
def listar_leitor():
    
    if request.method == 'POST':
        order_by = request.form.get('status')

        leitores = Leitor.listar(order_by)
        
        
        user = current_user
        return render_template('leitor.html', leitores=leitores, user = user)
    leitores = Leitor.all()
    user = current_user
    return render_template('leitor.html', leitores = leitores, user = user)


@bp.route('/dados_leitores/')
@login_required
def dados_leitores():
    leitores = Leitor.all()
    user = current_user
    return render_template("dados_leitores.html", leitores=leitores, user = user)

@bp.route('/editar_leitor/<int:id>', methods=['GET', 'POST'])
@login_required
def editar_leitor(id):
    

    if request.method == 'POST':
        nome = request.form.get('nome')
        email = request.form.get('email')
        telefone = request.form.get('telefone')
        endereco = request.form.get('endereco')
        Leitor.update(id, nome, email, telefone, endereco)
        return redirect(url_for('leitores.listar_leitor'))
    leitor = Leitor.one(id)
    user = current_user
    return render_template('editar_leitores.html', leitor = leitor, user = user)


@bp.route('/apagar_leitor/<int:id>')
@login_required
def excluir_leitor(id):
    lendings = Lending.listar("")
    for lending in lendings:
        if id == lending['len_lei_id']:
            mensagem = "Possui um empréstimo com esse Usuário, Impossível Excluir"
            leitores = Leitor.all()
            user = current_user
            return render_template("dados_leitores.html", leitores = leitores, mensagem = mensagem, user=user)
    Leitor.delete(id)
    return redirect(url_for('leitores.listar_leitor'))

Bluebook/controllers/Lending.py
from flask import Blueprint, render_template, request, url_for, redirect
from models.Lending import Lending
from models.Leitor import Leitor
from models.Book import Book
from database import obter_conexao
from flask_login import login_required, current_user
import ast

bp = Blueprint("lendings", __name__, url_prefix="/lendings")



@bp.route('/register_emprestimo', methods=['GET', 'POST'])
@login_required
def register_lending():
    if request.method == 'POST':
        usuario = request.form["usuario"]
        livro = request.form["livro"]
        devolucao = request.form["devolucao"]
        valor = request.form["valor"]
        user = current_user.id
        mensagem = Lending.cadastro(usuario=usuario, livro=livro, devolucao=devolucao, valor=valor, user = user)
        return redirect(url_for("lendings.listar_lending", mensagem=mensagem))

    else:
        consulta_leitores = Leitor.all()
        consulta_livros = Book.all()
        emprestimos = Lending.listar("")
        user = current_user
        return render_template('lending.html', consulta_livros=consulta_livros, consulta_leitores=consulta_leitores,emprestimos = emprestimos, user = user)
   

@bp.route('/listar_emprestimo', methods=['GET', 'POST'])
@login_required
def listar_lending():
    if request.method == 'POST':
        order_by = request.form.get('listar_emprestimos')

        emprestimos = Lending.listar(order_by)
        
        consulta_usuarios = Leitor.all()
        consulta_livros = Book.all()
        user = current_user
        if mensagem in request.args:
            mensagem = request.args.get("mensagem")
        return render_template('lending.html', emprestimos=emprestimos, consulta_livros=consulta_livros, consulta_usuarios=consulta_usuarios, user = user, mensagem=mensagem)
    emprestimos = Lending.listar("")
    consulta_usuarios = Leitor.all()
    consulta_livros = Book.all()
    user = current_user
    
    if "mensagem" in request.args:
            mensagem = request.args.get("mensagem")
            try:
                mensagem_dict = ast.literal_eval(mensagem)  # Converte string para dicionário real
                if isinstance(mensagem_dict, dict) and "@mensagem" in mensagem_dict:
                    mensagem = mensagem_dict["@mensagem"]  # Pega apenas o texto dentro do dicionário
            except (SyntaxError, ValueError):
                pass
    return render_template('lending.html', emprestimos=emprestimos , consulta_livros=consulta_livros, consulta_leitores=consulta_usuarios, user = user, mensagem= mensagem )

@bp.route('/dados_emprestimos/')
@login_required
def dados_emprestimos():
    emprestimos = Lending.all()
    user = current_user
    return render_template("dados_emprestimos.html", emprestimos = emprestimos, user = user)



@bp.route('/editar_empréstimo/<int:id>', methods=['GET', 'POST'])
@login_required
def editar_lending(id):
    

    if request.method == 'POST':
        leitor = request.form["leitor"]
        livro = request.form["livro"]
        valor = request.form["valor"]
        devolucao = request.form["data"]
        print(leitor,livro,valor,devolucao)
        Lending.update(leitor,livro, devolucao, valor,current_user.id, id)
        return redirect(url_for('lendings.dados_emprestimos'))
    
    lending = Lending.one(id)
    leitores = Leitor.all()
    books = Book.all()
    user = current_user
    return render_template('editar_emprestimos.html', emp=lending, user = user, leitores=leitores, books=books)


@bp.route('/apagar_empréstimo/<int:id>')
@login_required
def excluir_lending(id):
    Lending.delete(id)
    return redirect(url_for('lendings.dados_emprestimos'))

@bp.route('/devolver/<int:id>')
@login_required
def devolver(id):
    conn = obter_conexao()
    cursor = conn.cursor()
    query = 'UPDATE tb_lending SET len_devolvido =%s WHERE len_id = %s'
    cursor.execute(query, (True, id))
    conn.commit()
    cursor.close()
    conn.close()
    return redirect(url_for("lendings.dados_emprestimos"))

Bluebook/controllers/listagem.py
from flask import Blueprint, render_template, request, url_for, redirect
from models.Lending import Lending
from models.Leitor import Leitor
from models.Book import Book
from models.Listagem import Listagem
from flask_login import login_required, current_user

bp = Blueprint("listagem", __name__, url_prefix="/listagem")

@bp.route('/')
@login_required
def listagens():
    user = current_user
    return render_template("pg_listagem.html", user = user)


@bp.route('/filtro1', methods=['GET', 'POST'])
@login_required
def filtro1():
    
    if request.method == 'POST':
        use_id = request.form.get('usuario')
        data1 = request.form.get('data1')
        data2 = request.form.get('data2')
        total_emprestimos = Listagem.um(use_id, data1, data2)
        consulta_usuarios = Leitor.all()
        user = current_user
        return render_template('listagem_um.html', total_emprestimos=total_emprestimos, consulta_usuarios=consulta_usuarios, user = user)
    else:
        consulta_usuarios = Leitor.all()
        user = current_user
        return render_template('listagem_um.html', consulta_usuarios=consulta_usuarios, user = user)
    
@bp.route('/filtro2', methods=['GET', 'POST'])
@login_required
def filtro2():
    if request.method == 'POST':
        data1 = request.form.get('data1')
        data2 = request.form.get('data2')
        usuarios = Listagem.dois(data1, data2)
        user = current_user
        return render_template('listagem_dois.html', usuarios=usuarios, user = user)
    user = current_user
    return render_template('listagem_dois.html', user = user)

@bp.route('/filtro3', methods=['GET', 'POST'])
@login_required
def filtro3():
    if request.method == 'POST':
        dias = request.form.get('filtro_dias')
        livros = Listagem.tres(dias)
        user = current_user
        return render_template('listagem_tres.html', livros=livros, user = user)
    user = current_user
    return render_template('listagem_tres.html', user = user)

@bp.route('/filtro4', methods=['GET', 'POST'])
@login_required
def filtro4():
    if request.method == 'POST':
        dias = request.form.get('filtro_dias')
        livros = Listagem.quatro(dias)
        user = current_user
        return render_template('listagem_quatro.html', livros=livros, user = user)
    user = current_user
    return render_template('listagem_quatro.html', user = user)

@bp.route('/logs')
@login_required
def logs():
    user = current_user
    logs = Listagem.logs()
    return render_template("logs.html", user = user, logs=logs)

Bluebook/templates/book.html
{% extends 'index.html' %}
    {% block title %}
        Cadastro - Livros
    {% endblock %}
    {% block content %}
        <div class="container_cadliv" id="container_cadliv">
                <form class="form" method="post" action="{{ url_for('books.register_book' ) }}">
                    <br>
                    <h1>Novo Livro</h1>
                    <br>
                    <span style="margin-bottom: 5px;">Insira os dados e crie um novo livro
                    </span>
        
                    <label class="label-input" for="titulo">
                        <i class="fa-solid fa-heading"></i> <!--modificar p/ icon de livro-->
                        <input type="text" placeholder="Título do livro" for="titulo" name="titulo">
                    </label>
        
                    <label class="label-input" for="autor">
                        <i class="fa-solid fa-feather"></i> <!--modificar p/ icon de autor -->
                        <input type="text" placeholder="Nome do autor" for="autor" name="autor">
                    </label>
        
                    <label class="label-input" for="genero">
                        <i class="fa-solid fa-book"></i> <!--modificar p/ icon de genero de livro -->
                        <input type="text" placeholder="Gênero do livro" for="genero" name="genero">
                    </label>
        
                    <label class="label-input" for="isbn">
                        <i class="fa-solid fa-tag"></i> <!--modificar p/ icon de ISBN(nem sei o que é isso) -->
                        <input type="text" placeholder="ISBN" for="isbn" name="isbn">
                    </label>
                    
                    <label class="label-input" for="estoque">
                        <i class="fa-solid fa-box"></i><!--modificar p/ icon de estoque de livro -->
                        <input type="text" placeholder="Quantidade em estoque" for="estoque" name="estoque">
                    </label>
                    
                    <button type="submit">Concluir</button>
                </form>
        </div>

        <div class="container_cadliv" id="container_cadliv">
            <div class="container_user">
                <h1>Lista de Livros <a href="{{ url_for('books.dados_livros' ) }}">Detalhar</a></h1>

                <form method="post" class="filter-form" action="{{ url_for('books.listar_book' ) }}">
                    <div class="teste">
                        <div class="filter-group">
                            <label for="status">Filtrar:</label>
                            <select name="status" id="status">
                                <option value="asc">Aa-Zz</option>
                                <option value="desc">Zz-Aa</option>
                            </select>

                            <button type="submit" class="butao_filtrar">Filtrar</button>
                        </div>

                    </div>
                                   
                </form>
                <div class="table-scroll-container-2">
                    <table>
                        <tbody>
                            <!-- {% for book in books %} -->
                            <tr>
                                <td>{{ book.boo_titulo }}</td>
                            </tr>
                           
                            <!-- {% endfor %} -->
                        </tbody>
                    </table> 
                </div>                
            </div>
        </div>
    {% endblock %}
</body>

</html>

Bluebook/templates/dados_emprestimos.html
{% extends 'index.html' %}
{% block title %}
    Dados - Empréstimo
{% endblock %}

{% block content %}
    <div class="container_list container_list2" id="container_list">
        <div class="container_userd">
            <h1>Dados dos Empréstimos</h1>
            <h1 style="font-size: 20px;">{{mensagem}}</h1>
            <br>

            <div class="table-scroll-container">
                <table>
                    <thead>
                        <tr>
                            <th>Leitor</th>
                            <th>Livro</th>
                            <th>Foi Devolvido?</th>
                            <th>Valor</th>
                            <th>Data de Empréstimo</th>
                            <th>Data de Devolução</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for emp in emprestimos %}
                            <tr>
                                <td>{{ emp.lei_nome }}</td>
                                <td>{{ emp.boo_titulo }}</td>
                                <td>
                                    {% if emp.len_devolvido == 0 %}
                                        Não
                                    {% else %}
                                        Sim
                                    {% endif %}
                                </td>
                                <td>{{ emp.len_valor }}</td>
                                <td>{{ emp.len_data_emprestimo }}</td>
                                <td>{{ emp.len_data_devolucao }}</td>
                                <td id="td-button">
                                    <button type="submit" id="editar">
                                        <a href="{{ url_for('lendings.editar_lending', id=emp.len_id) }}" style="text-decoration: none; color: white;">Editar</a>
                                    </button>
                                    <button type="submit" id="excluir">
                                        <a href="{{ url_for('lendings.excluir_lending', id=emp.len_id) }}" style="text-decoration: none; color: white;">Excluir</a>
                                    </button>
                                    <button class="devolver"><a href="{{ url_for('lendings.devolver', id=emp.len_id) }}" style="text-decoration: none; color: white;">Devolver</a></button>
                                </td>
                            </tr> 
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

Bluebook/templates/dados_leitores.html
{% extends 'index.html' %}
    {% block title %}
        Dados - Usuário
    {% endblock %}
    {% block content %}
    

        <div class="container_list container_list2" id="container_list">
            <div class="container_userd">
                <h1>Dados do Usuário</h1>
                <h1 style="font-size: 20px;">{{mensagem}}</h1>
                <br>

                <div class="table-scroll-container">

                    <table>
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Endereço</th>
                                <th>Telefone</th>
                                <th>Email</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for leitor in leitores %}
                            <tr>
                                <td>{{leitor.lei_nome}}</td>
                                <td>{{leitor.lei_endereco}}</td>
                                <td>{{leitor.lei_telefone}}</td>
                                <td>{{leitor.lei_email}}</td>
                                <td id="td-button">
                                    <button type="submit" id="editar"><a href="{{ url_for('leitores.editar_leitor', id=leitor.lei_id) }}" style="text-decoration: none; color: white;">Editar</a></button>
                                    <button type="submit" id="excluir"><a href="{{ url_for('leitores.excluir_leitor', id=leitor.lei_id) }}" style="text-decoration: none; color: white;">Excluir</a></button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        
                    </table>
                    
                </div>
                
            </div>
            
        </div>
    {% endblock %}
</body>

</html>

Bluebook/templates/dados_livros.html
{% extends 'index.html' %}
{% block title %}
    Dados - Livros
{% endblock %}
    {% block content %}
        
    
        <div class="container_list container_list2" id="container_list">
            <div class="container_userd">
                <h1>Dados dos Livros</h1>
                <h1 style="font-size: 20px;">{{mensagem}}</h1>
                <br>

                <div class="table-scroll-container">

                    <table>
                        <thead>
                            <tr>
                                <th>Título</th>
                                <th>Autor</th>
                                <th>Gênero</th>
                                <th>ISBN</th>
                                <th>Quant. Estoque</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for book in books %}
                                
                            
                            <tr>
                                <td>{{book.boo_titulo}}</td>
                                <td>{{book.boo_autor}}</td>
                                <td>{{book.boo_genero}}</td>
                                <td>{{book.boo_isbn}}</td>
                                <td>{{book.boo_quant_estoque}}</td>
                                <td id="td-button">
                                    <button type="submit" id="editar"><a href="{{ url_for('books.editar_book', id=book.boo_id) }}" style="text-decoration: none; color: white;">Editar</a></button>
                                    <button type="submit" id="excluir"><a href="{{ url_for('books.excluir_book', id=book.boo_id) }}" style="text-decoration: none; color: white;">Excluir</a></button>
                                </td>
                            </tr> 
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    {% endblock %}

</body>

</html>

Bluebook/templates/leitor.html
{% extends 'index.html' %}
    {% block title %}
        Cadastro - Leitor
    {% endblock %}
    {% block content %}
        <div class="container_cadliv" id="container_cadliv">
                <form class="form" method="post" action="{{ url_for('leitores.register_leitor' ) }}">
                    <br>
                    <h1>Novo Leitor</h1>
                    <br>
                    <span style="margin-bottom: 5px;">Insira os dados e crie um novo leitor
                    </span> 

                    <label class="label-input" for="nome">
                        <i class="fa-solid fa-user"></i>
                        <input type="text" placeholder="Nome do Usuário " for="nome" name="nome">
                    </label>
                    
                    <label class="label-input" for="email">
                        <i class="far fa-envelope icon-modify"></i>
                        <input type="email" placeholder="usuario@example.com" for="email" name="email">
                    </label>
                    
                    <label class="label-input" for="telefone">
                        <i class="fa-solid fa-phone"></i>
                        <input type="tel" placeholder="(XX) XXXX-XXXX" for="telefone" name="telefone">
                    </label>
                    
                    <label class="label-input" for="endereco">
                        <i class="fa-sharp fa-solid fa-location-dot"></i>
                        <input type="text" placeholder="Endereço" for="endereco" name="endereco">
                    </label>
                 
                    <button type="submit">Concluir</button>
                </form>
        </div>

        <div class="container_cadliv" id="container_cadliv">
            <div class="container_user">
                <h1>Lista de Usuários <a href="{{ url_for('leitores.dados_leitores' ) }}">Detalhar</a></h1>

                <form method="post" class="filter-form" action="{{ url_for('leitores.listar_leitor' ) }}">
                    <div class="teste">
                        <div class="filter-group">
                            <label for="status">Filtrar:</label>
                            <select name="status" id="status">
                                <option value="">Aa-Zz</option>
                                <option value="desc">Zz-Aa</option>
                            </select>

                            <button type="submit" class="butao_filtrar">Filtrar</button>
                        </div>

                    </div>
                                   
                </form>
                <div class="table-scroll-container-2">
                    <table>
                        <tbody>
                            {% for leitor in leitores %}
                            <tr>
                                <td>{{leitor.lei_nome }}</td>
                            </tr>
                           
                            {% endfor %}
                        </tbody>
                    </table> 
                </div>
                
            </div>
        </div>
    {% endblock %}
</body>

</html>

Bluebook/templates/pg_listagem.html
{% extends 'index.html' %}
    {% block title %}
        Listagens
    {% endblock %}
    {% block content %}
        
    
        <div class="intro_cadliv">
            <h3>Empréstimos em Real</h3>
            <br>
            <p>Use a função "Empréstimos em Real" para detalhar os empréstimos de cada leitor em reais</p>
            <img class="image-index-list" src="{{ url_for('static', filename='images/index-list.svg') }}" alt="Imagem" >
            <br>

            <a href="{{url_for('listagem.filtro1')}}"><button>Entrar</button></a>
        </div>

        <div class="intro_cadliv">
            <h3>Empréstimos acima de R$100,00</h3>
            <br>
            <p>Use a função "Empréstimos acima de R$100,00" para filtrar os empréstimos dos leitores</p>
            <img class="image-index-list" src="{{ url_for('static', filename='images/index-list.svg') }}" alt="Imagem" >
            <br>
            <a href="{{url_for('listagem.filtro2')}}"><button>Entrar</button></a>
        </div>

        <div class="intro_cadliv">
            <h3>Top 10 Livros mais pedidos</h3>
            <br>
            <p>Use a função "Top 10 livros mais pedidos" para ranquear os melhores para os leitores</p>
            <img class="image-index-list" src="{{ url_for('static', filename='images/index-list.svg') }}" alt="Imagem" >
            <br>
            <a href="{{url_for('listagem.filtro3')}}"><button>Entrar</button></a>
        </div>

        <div class="intro_cadliv">
            <h3>Livros não foram emprestados</h3>
            <br>
            <p>Use a função "Livros não foram emprestados" para filtrar os piores para os leitores</p>
            <img class="image-index-list" src="{{ url_for('static', filename='images/index-list.svg') }}" alt="Imagem" >
            <br>
            <a href="{{url_for('listagem.filtro4')}}"><button>Entrar</button></a>
        </div>

    {% endblock %}
</body>
</html>